name: build
on:
    push:
        branches:
            - "**"

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macOS-latest
                    - windows-latest
        steps:
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.16

            - name: Setup Just
              uses: extractions/setup-just@v3
              with:
                  just-version: '1.40.0'

            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              run: just build test

            - name: Convert Coverage Format to LCOV
              uses: jandelgado/gcov2lcov-action@v1.0.0
              if: matrix.os == 'ubuntu-latest'
              with:
                  infile: coverage.out
                  outfile: coverage.lcov

            - name: Coveralls
              uses: coverallsapp/github-action@v1.0.1
              if: matrix.os == 'ubuntu-latest'
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: coverage.lcov
